name: deploy now
description: deploy to zeit's now on push
inputs:
  github_token:
    required: true
    description: API token for GitHub
    default: ${{ github.token }}
  zeit_token:
    required: true
    description: API token for Zeit with access to this project
  prod:
    required: false
    description: If true, then deploys the production site now
    default: false
  skip_comment:
    required: false
    description: If true, then no comment will be posted to PRs or commits after a deploy
    default: false
  debug:
    required: false
    description: If true, then output debugging information
    default: false
outputs:
  deployment_url:
    description: Deployment logs on the Zeit dashboard
  preview_alias:
    description: Public alias to preview the deployed site
  preview_alias_url:
    description: Same as above with https://
runs:
  using: node12
  main: dist/index.js
